### ISSUE TITLE
Implement members feature

### ISSUE THREAD

**Issue by elevenpassin** [coderplex-org/coderplex-backend#3]
# Overview
- [ ] I can search a list of users.
- [ ] I can view more information about a user, build experience
- [ ] I can add new members and edit details of members
- [ ] I can filter members by skill, job etc

# In detail
- [x] Implement models for members and projects (#2)
- [x] Implement graphql types for members and projects (#5)
- [ ] Implement resolvers for members and projects (#4)
- [ ] Implement Authentication (#6)
- [ ] Import existing user data and provide a way for users to setup their account
- [ ] Implement filtering and pagination features
